//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MapSolution
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyReleaseDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyReleaseDBEntities object using the connection string found in the 'MyReleaseDBEntities' section of the application configuration file.
        /// </summary>
        public MyReleaseDBEntities() : base("name=MyReleaseDBEntities", "MyReleaseDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyReleaseDBEntities object.
        /// </summary>
        public MyReleaseDBEntities(string connectionString) : base(connectionString, "MyReleaseDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyReleaseDBEntities object.
        /// </summary>
        public MyReleaseDBEntities(EntityConnection connection) : base(connection, "MyReleaseDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<CityFamilyCountResult> GetCityFamilyCount()
        {
            return base.ExecuteFunction<CityFamilyCountResult>("GetCityFamilyCount");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<LatlongDataResult> GetLatlongData()
        {
            return base.ExecuteFunction<LatlongDataResult>("GetLatlongData");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyReleaseDBModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personID">Initial value of the PersonID property.</param>
        public static Person CreatePerson(global::System.Guid personID)
        {
            Person person = new Person();
            person.PersonID = personID;
            return person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PersonID
        {
            get
            {
                return _PersonID;
            }
            set
            {
                if (_PersonID != value)
                {
                    OnPersonIDChanging(value);
                    ReportPropertyChanging("PersonID");
                    _PersonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonID");
                    OnPersonIDChanged();
                }
            }
        }
        private global::System.Guid _PersonID;
        partial void OnPersonIDChanging(global::System.Guid value);
        partial void OnPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PersonSearchID
        {
            get
            {
                return _PersonSearchID;
            }
            set
            {
                OnPersonSearchIDChanging(value);
                ReportPropertyChanging("PersonSearchID");
                _PersonSearchID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PersonSearchID");
                OnPersonSearchIDChanged();
            }
        }
        private global::System.String _PersonSearchID;
        partial void OnPersonSearchIDChanging(global::System.String value);
        partial void OnPersonSearchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitType
        {
            get
            {
                return _UnitType;
            }
            set
            {
                OnUnitTypeChanging(value);
                ReportPropertyChanging("UnitType");
                _UnitType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitType");
                OnUnitTypeChanged();
            }
        }
        private global::System.String _UnitType;
        partial void OnUnitTypeChanging(global::System.String value);
        partial void OnUnitTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip_code
        {
            get
            {
                return _zip_code;
            }
            set
            {
                Onzip_codeChanging(value);
                ReportPropertyChanging("zip_code");
                _zip_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zip_code");
                Onzip_codeChanged();
            }
        }
        private global::System.String _zip_code;
        partial void Onzip_codeChanging(global::System.String value);
        partial void Onzip_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> IMS_data_latitude
        {
            get
            {
                return _IMS_data_latitude;
            }
            set
            {
                OnIMS_data_latitudeChanging(value);
                ReportPropertyChanging("IMS_data_latitude");
                _IMS_data_latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IMS_data_latitude");
                OnIMS_data_latitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _IMS_data_latitude;
        partial void OnIMS_data_latitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnIMS_data_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> IMS_data_longitude
        {
            get
            {
                return _IMS_data_longitude;
            }
            set
            {
                OnIMS_data_longitudeChanging(value);
                ReportPropertyChanging("IMS_data_longitude");
                _IMS_data_longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IMS_data_longitude");
                OnIMS_data_longitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _IMS_data_longitude;
        partial void OnIMS_data_longitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnIMS_data_longitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String county
        {
            get
            {
                return _county;
            }
            set
            {
                OncountyChanging(value);
                ReportPropertyChanging("county");
                _county = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("county");
                OncountyChanged();
            }
        }
        private global::System.String _county;
        partial void OncountyChanging(global::System.String value);
        partial void OncountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CenterName
        {
            get
            {
                return _CenterName;
            }
            set
            {
                OnCenterNameChanging(value);
                ReportPropertyChanging("CenterName");
                _CenterName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CenterName");
                OnCenterNameChanged();
            }
        }
        private global::System.String _CenterName;
        partial void OnCenterNameChanging(global::System.String value);
        partial void OnCenterNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CenterType
        {
            get
            {
                return _CenterType;
            }
            set
            {
                OnCenterTypeChanging(value);
                ReportPropertyChanging("CenterType");
                _CenterType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CenterType");
                OnCenterTypeChanged();
            }
        }
        private global::System.String _CenterType;
        partial void OnCenterTypeChanging(global::System.String value);
        partial void OnCenterTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionName
        {
            get
            {
                return _RegionName;
            }
            set
            {
                OnRegionNameChanging(value);
                ReportPropertyChanging("RegionName");
                _RegionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegionName");
                OnRegionNameChanged();
            }
        }
        private global::System.String _RegionName;
        partial void OnRegionNameChanging(global::System.String value);
        partial void OnRegionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RelationType
        {
            get
            {
                return _RelationType;
            }
            set
            {
                OnRelationTypeChanging(value);
                ReportPropertyChanging("RelationType");
                _RelationType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RelationType");
                OnRelationTypeChanged();
            }
        }
        private global::System.String _RelationType;
        partial void OnRelationTypeChanging(global::System.String value);
        partial void OnRelationTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MandalName
        {
            get
            {
                return _MandalName;
            }
            set
            {
                OnMandalNameChanging(value);
                ReportPropertyChanging("MandalName");
                _MandalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MandalName");
                OnMandalNameChanged();
            }
        }
        private global::System.String _MandalName;
        partial void OnMandalNameChanging(global::System.String value);
        partial void OnMandalNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZoneName
        {
            get
            {
                return _ZoneName;
            }
            set
            {
                OnZoneNameChanging(value);
                ReportPropertyChanging("ZoneName");
                _ZoneName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZoneName");
                OnZoneNameChanged();
            }
        }
        private global::System.String _ZoneName;
        partial void OnZoneNameChanging(global::System.String value);
        partial void OnZoneNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_Info_RegionName
        {
            get
            {
                return _Center_Info_RegionName;
            }
            set
            {
                OnCenter_Info_RegionNameChanging(value);
                ReportPropertyChanging("Center_Info_RegionName");
                _Center_Info_RegionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_Info_RegionName");
                OnCenter_Info_RegionNameChanged();
            }
        }
        private global::System.String _Center_Info_RegionName;
        partial void OnCenter_Info_RegionNameChanging(global::System.String value);
        partial void OnCenter_Info_RegionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_Info_CenterName
        {
            get
            {
                return _Center_Info_CenterName;
            }
            set
            {
                OnCenter_Info_CenterNameChanging(value);
                ReportPropertyChanging("Center_Info_CenterName");
                _Center_Info_CenterName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_Info_CenterName");
                OnCenter_Info_CenterNameChanged();
            }
        }
        private global::System.String _Center_Info_CenterName;
        partial void OnCenter_Info_CenterNameChanging(global::System.String value);
        partial void OnCenter_Info_CenterNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CenterAddress1
        {
            get
            {
                return _CenterAddress1;
            }
            set
            {
                OnCenterAddress1Changing(value);
                ReportPropertyChanging("CenterAddress1");
                _CenterAddress1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CenterAddress1");
                OnCenterAddress1Changed();
            }
        }
        private global::System.String _CenterAddress1;
        partial void OnCenterAddress1Changing(global::System.String value);
        partial void OnCenterAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CenterAddress2
        {
            get
            {
                return _CenterAddress2;
            }
            set
            {
                OnCenterAddress2Changing(value);
                ReportPropertyChanging("CenterAddress2");
                _CenterAddress2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CenterAddress2");
                OnCenterAddress2Changed();
            }
        }
        private global::System.String _CenterAddress2;
        partial void OnCenterAddress2Changing(global::System.String value);
        partial void OnCenterAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_Infozip_code
        {
            get
            {
                return _Center_Infozip_code;
            }
            set
            {
                OnCenter_Infozip_codeChanging(value);
                ReportPropertyChanging("Center_Infozip_code");
                _Center_Infozip_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_Infozip_code");
                OnCenter_Infozip_codeChanged();
            }
        }
        private global::System.String _Center_Infozip_code;
        partial void OnCenter_Infozip_codeChanging(global::System.String value);
        partial void OnCenter_Infozip_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_latitude
        {
            get
            {
                return _Center_latitude;
            }
            set
            {
                OnCenter_latitudeChanging(value);
                ReportPropertyChanging("Center_latitude");
                _Center_latitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_latitude");
                OnCenter_latitudeChanged();
            }
        }
        private global::System.String _Center_latitude;
        partial void OnCenter_latitudeChanging(global::System.String value);
        partial void OnCenter_latitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_longitude
        {
            get
            {
                return _Center_longitude;
            }
            set
            {
                OnCenter_longitudeChanging(value);
                ReportPropertyChanging("Center_longitude");
                _Center_longitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_longitude");
                OnCenter_longitudeChanged();
            }
        }
        private global::System.String _Center_longitude;
        partial void OnCenter_longitudeChanging(global::System.String value);
        partial void OnCenter_longitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_Info_city
        {
            get
            {
                return _Center_Info_city;
            }
            set
            {
                OnCenter_Info_cityChanging(value);
                ReportPropertyChanging("Center_Info_city");
                _Center_Info_city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_Info_city");
                OnCenter_Info_cityChanged();
            }
        }
        private global::System.String _Center_Info_city;
        partial void OnCenter_Info_cityChanging(global::System.String value);
        partial void OnCenter_Info_cityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_Info_state
        {
            get
            {
                return _Center_Info_state;
            }
            set
            {
                OnCenter_Info_stateChanging(value);
                ReportPropertyChanging("Center_Info_state");
                _Center_Info_state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_Info_state");
                OnCenter_Info_stateChanged();
            }
        }
        private global::System.String _Center_Info_state;
        partial void OnCenter_Info_stateChanging(global::System.String value);
        partial void OnCenter_Info_stateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Center_Info_county
        {
            get
            {
                return _Center_Info_county;
            }
            set
            {
                OnCenter_Info_countyChanging(value);
                ReportPropertyChanging("Center_Info_county");
                _Center_Info_county = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Center_Info_county");
                OnCenter_Info_countyChanged();
            }
        }
        private global::System.String _Center_Info_county;
        partial void OnCenter_Info_countyChanging(global::System.String value);
        partial void OnCenter_Info_countyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Distance_2
        {
            get
            {
                return _Distance_2;
            }
            set
            {
                OnDistance_2Changing(value);
                ReportPropertyChanging("Distance_2");
                _Distance_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Distance_2");
                OnDistance_2Changed();
            }
        }
        private global::System.String _Distance_2;
        partial void OnDistance_2Changing(global::System.String value);
        partial void OnDistance_2Changed();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="MyReleaseDBModel", Name="CityFamilyCountResult")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CityFamilyCountResult : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip_code
        {
            get
            {
                return _zip_code;
            }
            set
            {
                Onzip_codeChanging(value);
                ReportPropertyChanging("zip_code");
                _zip_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zip_code");
                Onzip_codeChanged();
            }
        }
        private global::System.String _zip_code;
        partial void Onzip_codeChanging(global::System.String value);
        partial void Onzip_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Distance
        {
            get
            {
                return _Distance;
            }
            set
            {
                OnDistanceChanging(value);
                ReportPropertyChanging("Distance");
                _Distance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Distance");
                OnDistanceChanged();
            }
        }
        private Nullable<global::System.Double> _Distance;
        partial void OnDistanceChanging(Nullable<global::System.Double> value);
        partial void OnDistanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FamilyCount
        {
            get
            {
                return _FamilyCount;
            }
            set
            {
                OnFamilyCountChanging(value);
                ReportPropertyChanging("FamilyCount");
                _FamilyCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FamilyCount");
                OnFamilyCountChanged();
            }
        }
        private Nullable<global::System.Int32> _FamilyCount;
        partial void OnFamilyCountChanging(Nullable<global::System.Int32> value);
        partial void OnFamilyCountChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="MyReleaseDBModel", Name="LatlongDataResult")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class LatlongDataResult : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> latitude
        {
            get
            {
                return _latitude;
            }
            set
            {
                OnlatitudeChanging(value);
                ReportPropertyChanging("latitude");
                _latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("latitude");
                OnlatitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _latitude;
        partial void OnlatitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnlatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> longtitude
        {
            get
            {
                return _longtitude;
            }
            set
            {
                OnlongtitudeChanging(value);
                ReportPropertyChanging("longtitude");
                _longtitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("longtitude");
                OnlongtitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _longtitude;
        partial void OnlongtitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnlongtitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FamilyCount
        {
            get
            {
                return _FamilyCount;
            }
            set
            {
                OnFamilyCountChanging(value);
                ReportPropertyChanging("FamilyCount");
                _FamilyCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FamilyCount");
                OnFamilyCountChanged();
            }
        }
        private Nullable<global::System.Int32> _FamilyCount;
        partial void OnFamilyCountChanging(Nullable<global::System.Int32> value);
        partial void OnFamilyCountChanged();

        #endregion

    }

    #endregion

    
}
